- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: ubuntu
    package:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (CentOS)
    tags: centos
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  roles:
    - cinder
    - horizon
    - neutron

